### ISSUE TITLE
How to make policies to deal with exceptional/ "edge case" scenarios?

### ISSUE THREAD

**Issue by alethkit** [SRCF/governance-working-group#3]

**Comment by LimaBravoVictor** [comment]
It will not be possible to handle all edge cases. 
Rather, we should come up with a set of core principles, which are applied to these edge cases and new policy created as appropriate. This way, the society's governance will learn and improve over time, and can adapt to changing circumstances.

**Comment by CHTJonas** [comment]
Exception circumstances should be dealt with by the committee/sysadmins in line with high-level policy objectives as & when they arise. There's no point us coming up with detailed policies that cover every single possible edge case; that's simply unrealistic.

**Comment by CHTJonas** [comment]
However, it is important that any decisions made in exceptional circumstances are documented so that they might be appealed, if and as appropriate, or referred back to in future, should they be repeated.

**Comment by alethkit** [comment]
Well, yes!

So the question then becomes - where do they get documented?

I strongly believe having them spread out throughout disparate pages of documentation is not helpful in the slightest.

I would suggest having a dedicated page that documents these ‘exceptional’ circumstances.

Perhaps a slight modification of what is in https://www.ocf.berkeley.edu/docs/docs/policies/ would suffice.

**Comment by CHTJonas** [comment]
Again, I'm not a sysadmin or committee member, but I'd suggest that the outcome of decision and the decision making process should probably be documented on the executive wiki. User-facing policy stuff should be on the SRCF public website.

When you refer to stuff being "spread out throughout disparate pages of documentation", is there something specific you're thinking of? Could this be better resolved with a PR to {www,docs}.srcf.net perhaps?

Again, I would avoid documenting what constitutes exceptional circumstances. Give the executive the breathing room they need to act!

**Comment by alethkit** [comment]
>  "spread out throughout disparate pages of documentation", is there something specific you're thinking of?

Contrast our current spread between the official documents, volunteer documentation, and internal wiki with https://bestdocs.ocf.io [everything is *easily* accessible, although I still have some minor quibbles about the information architecture. private documentation is also indicated, but locked.]

Much easier for *anyone* (whether it be interested onlooker, member, volunteer, sysadmin or committee member) to figure out how the society works and how to do things.

It's the less visible things that end up deterring participation - not many people are willing to trawl through years of archives/ meeting records/websites, or permanently lurk on IRC/Discord to make a simple contribution.
